version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libredte_app
    volumes:
      - .:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER="1"
      - DB_HOST=db
      - DB_NAME=${MYSQL_DB:-libredte}
      - DB_USER=${SERVICE_USER_MYSQL}
      - DB_PASSWORD=${SERVICE_PASSWORD_MYSQL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MESSENGER_REDIS_DSN=${REDIS_URL:-redis://localhost:6379}
    depends_on:
      - db
      - redis
    # Coolify espera que tu app exponga el puerto 80 internamente
    expose:
      - "80"

  db:
    image: mysql:8
    container_name: libredte_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_MYSQLROOT}
      - MYSQL_DATABASE=${MYSQL_DB:-libredte}
      - MYSQL_USER=${SERVICE_USER_MYSQL}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_MYSQL}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: libredte_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data: