version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libredte_app
    volumes:
      - .:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER="1"
      - DB_HOST=db
      - DB_NAME=${PGSQL_DB:-libredte}
      - DB_USER=${SERVICE_USER_PGSQL}
      - DB_PASSWORD=${SERVICE_PASSWORD_PGSQL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MESSENGER_REDIS_DSN=${REDIS_URL:-redis://localhost:6379}
    depends_on:
      - db
      - redis
    # Coolify espera que tu app exponga el puerto 80 internamente
    expose:
      - "80"

  db:
    image: postgres:13
    container_name: libredte_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${SERVICE_USER_PGSQL}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_PGSQL}
      - POSTGRES_DB=${PGSQL_DB:-libredte}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: libredte_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data: