version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libredte_app
    volumes:
      - .:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      DB_HOST: db
      DB_NAME: libredte
      DB_USER: libredte
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    # Coolify espera que tu app exponga el puerto 80 internamente
    expose:
      - "80"
    networks:
      - libredte_network

  db:
    image: mysql:5.7
    container_name: libredte_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: libredte
      MYSQL_USER: libredte
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - libredte_network

  redis:
    image: redis:alpine
    container_name: libredte_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - libredte_network

volumes:
  db_data:

networks:
  libredte_network:
    driver: bridge