version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libredte_app
    volumes:
      - .:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      DB_HOST: db
      DB_NAME: libredte
      DB_USER: libredte
      DB_PASSWORD: secret
    depends_on:
      - db
    # Coolify espera que tu app exponga el puerto 80 internamente
    expose:
      - "80"

  db:
    image: mysql:5.7
    container_name: libredte_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: libredte
      MYSQL_USER: libredte
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: